---

- name: Install MySQL server
  apt: pkg=mysql-server state=present
  sudo: yes

- name: Install Python MySQL bindings
  apt: pkg=python-mysqldb state=present
  sudo: yes

- name: Install Git
  apt: pkg=git-core state=present
  sudo: yes

- name: Create CH parent dir
  file: path={{ ch_parent_dir }} owner={{capehub_user}} group={{capehub_group}} state=directory
  sudo: yes

- name: Fix CH parent dir permissions
  file: path={{ch_parent_dir}}/ owner={{capehub_user}} group={{capehub_group}} state=directory recurse=true
  sudo: true

- name: Create CH shared dir
  file: path={{ch_work_dir}} owner={{capehub_user}} group={{capehub_group}} state=directory

- include: ../../common/tasks/clone_mh.yml

- include: ../../common/tasks/clean_db.yml

- name: MySQL ROOT Granting user permissions on DB
  mysql_user: login_user=root login_password= name={{db_user}} password={{db_pass}} host="%" priv="{{db_schema}}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX"

- name: Allowing remote MySQL connections
  shell: sed -i 's/bind-address/#bind-address/g' /etc/mysql/my.cnf
  sudo: yes

- name: Restarting MySQL
  service: name=mysql state=restarted
  sudo: yes
